name: sbom-ops-sync

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "17 * * * *"

permissions:
  contents: read
  issues: write

concurrency:
  group: sbom-ops-sync-${{ github.ref }}
  cancel-in-progress: false

jobs:
  sync:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.12"
      - run: python -m pip install .
      - run: sbom-ops sync
        env:
          SBOM_OPS_DT_BASE_URL: ${{ secrets.SBOM_OPS_DT_BASE_URL }}
          SBOM_OPS_DT_API_KEY: ${{ secrets.SBOM_OPS_DT_API_KEY }}
          SBOM_OPS_GITHUB_TOKEN: ${{ secrets.SBOM_OPS_GITHUB_TOKEN }}
          SBOM_OPS_GITHUB_OWNER: ${{ vars.SBOM_OPS_GITHUB_OWNER }}
          SBOM_OPS_GITHUB_REPO: ${{ vars.SBOM_OPS_GITHUB_REPO }}
